"""Generate docs/11_VALIDATION_REPORT.md from the built artefacts.

Every number in the validation report is read from data/serve/validation.json
and artifacts/forecast/metadata.json, never typed by hand, so the report cannot
drift from what the system actually does.

    python scripts/make_report.py
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
V = json.loads((ROOT / "data" / "serve" / "validation.json").read_text(encoding="utf-8"))
MONTHS = "Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split()


def f(x, d=2):
    return "–" if x is None else f"{x:,.{d}f}"


def pct(x, d=0):
    return "–" if x is None else f"{100 * x:.{d}f}%"


def main() -> None:
    a, fc, risk = V["alerts"], V["forecast"], V["risk"]
    H = {int(k): v for k, v in fc["horizons"].items()}
    L = []
    w = L.append

    w("# Validation Report\n")
    w(f"> Generated by `scripts/make_report.py` on {date.today().isoformat()} from `data/serve/validation.json` "
      "and `artifacts/forecast/metadata.json`. Do not edit by hand.\n")

    w("## 1. Does an impact-based index beat a temperature threshold?\n")
    w(f"All {a['cellDays']:,} in-state cell-days, 2015–2025, compared with an IMD-style rule (daily maximum temperature ≥ 40 °C).\n")
    w("| Measure | Value |\n| --- | --- |")
    w(f"| Supplied notebook: days flagged Red | **{a['notebookRedDaysPct']}%** |")
    summer_w = a["summerBandSharesPct"].get("Warning", 0) + a["summerBandSharesPct"].get("Emergency", 0)
    w(f"| USHMA: March–June days at Warning or Emergency | **{summer_w:.1f}%** |")
    w(f"| All days: temperature rule fires | {a['rateImdPct']}% |")
    w(f"| All days: USHMA Warning+ | {a['rateUshmaPct']}% |")
    w(f"| USHMA alerts the temperature rule **misses** | **{a['ushmaMissedByTempPct']}%** (mean Tmax {a['missedMeanTmax']} °C, mean WBGT {a['missedMeanWbgt']} °C) |")
    w(f"| Temperature alerts USHMA does not raise | {a['tempAlertsNotUshmaPct']}% (mean WBGT {a['overMeanWbgt']} °C — dry heat, sweating still works) |")
    w(f"| July–August: temperature-rule alerts | **{a['julAugImd']}** |")
    w(f"| July–August: USHMA Warning+ | **{a['julAugUshma']:,}** |\n")
    w("### By month (% of cell-days)\n")
    w("| Month | USHMA Warning+ | Tmax ≥ 40 °C |\n| --- | --- | --- |")
    for m in a["monthly"]:
        w(f"| {MONTHS[m['month'] - 1]} | {m['ushma']:.2f} | {m['imd']:.2f} |")
    w("")

    w("## 2. Forecast skill (held-out 2024–2025)\n")
    w(f"Train 2015-01-01 to {fc['train_end']}, calibrate on {fc['valid_end'][:4]}, test 2024–2025. "
      "Mean absolute error of HTSI (0–100 scale).\n")
    w("| Lead | Model MAE | Persistence | Climatology | Skill vs persistence | Skill vs climatology | Summer MAE (model / persist.) |")
    w("| --- | --- | --- | --- | --- | --- | --- |")
    for h in sorted(H):
        r = H[h]
        w(f"| D+{h} | **{f(r['mae_model'])}** | {f(r['mae_persistence'])} | {f(r['mae_climatology'])} | "
          f"{pct(r['skill_vs_persistence'])} | {pct(r['skill_vs_climatology'])} | {f(r['mae_model_summer'])} / {f(r['mae_persistence_summer'])} |")
    w("")

    w("## 3. Are the stated uncertainty bands honest?\n")
    w("Share of held-out outcomes inside the 80% band.\n")
    w("| Lead | Raw quantile regression | After split-conformal calibration | Conformal widening (HTSI pts) | Mean band width |")
    w("| --- | --- | --- | --- | --- |")
    for h in sorted(H):
        r = H[h]
        w(f"| D+{h} | {pct(r['coverage_80_raw'], 1)} | **{pct(r['coverage_80_conformal'], 1)}** | ±{f(r['conformal_qhat'])} | {f(r['band_width_mean'], 1)} |")
    w("")

    w("## 4. Catching dangerous days\n")
    E = {int(k): v for k, v in fc.get("exceedance", {}).items()}
    w(f"Warning-or-worse days (HTSI ≥ {fc['warning_edge']}) are about 1% of held-out days. The quantile median is the right "
      "point forecast and the wrong alarm: it shrinks toward typical values and never predicted a single Warning day "
      "(F1 = 0 at every lead). Alerts therefore come from dedicated exceedance classifiers whose decision threshold was "
      "tuned on 2023 and frozen before 2024–2025 were scored.\n")
    for level in ("warning", "watch"):
        w(f"### {level.title()} or worse\n")
        w("| Lead | Threshold | AUC | PR-AUC (base rate) | F1 | Precision / recall | Persistence F1 | Brier skill |")
        w("| --- | --- | --- | --- | --- | --- | --- | --- |")
        for h in sorted(E):
            x = E[h][level]
            w(f"| D+{h} | {x['threshold']:.2f} | {x['auc']:.3f} | {x['pr_auc']:.3f} ({x['pr_auc_base']:.3f}) | **{x['model']['f1']:.3f}** | "
              f"{x['model']['precision']:.2f} / {x['model']['recall']:.2f} | {x['persistence']['f1']:.3f} | {pct(x['brier_skill_vs_base_rate'])} |")
        w("")
    w("| Lead | Median-forecast F1, for reference |\n| --- | --- |")
    for h in sorted(H):
        w(f"| D+{h} | {f(H[h]['warning_model']['f1'], 3)} |")
    w("")

    w("## 5. What the model relies on (mean |SHAP|, D+1)\n")
    w("| Feature | Mean \\|SHAP\\| (HTSI pts) |\n| --- | --- |")
    for s in fc.get("shap", {}).get("1", [])[:10]:
        w(f"| {s['label']} | {s['mean_abs_shap']:.2f} |")
    w("")

    w("## 6. Heat-attributable mortality\n")
    w("| Year | Attributable deaths | Low | High | % of all deaths | NCRB certified heatstroke |")
    w("| --- | --- | --- | --- | --- | --- |")
    for r in risk["annual"]:
        w(f"| {r['year']} | {r['excess_deaths']:,.0f} | {r['excess_low']:,.0f} | {r['excess_high']:,.0f} | "
          f"{r['attributable_fraction_pct']} | {int(r['ncrb_heatstroke']) if r.get('ncrb_heatstroke') is not None else '–'} |")
    y23 = next((r for r in risk["annual"] if r["year"] == 2023), None)
    if y23:
        w(f"\n2023: {y23['excess_deaths']:,.0f} modelled attributable deaths against {risk['ncrb']['heatstroke']} certified heatstroke deaths "
          f"(ratio {y23['excess_deaths'] / risk['ncrb']['heatstroke']:.0f}). Certified heatstroke is a small, under-ascertained subset of heat-attributable "
          "all-cause mortality, so a gap of one to two orders of magnitude is expected. This checks plausibility, not calibration.\n")
    w("### By month, all years\n")
    w("| Month | Deaths |\n| --- | --- |")
    for m, x in sorted(risk["byMonth"].items(), key=lambda kv: int(kv[0])):
        w(f"| {MONTHS[int(m) - 1]} | {x:,.0f} |")
    w("")

    w("## 7. Vulnerability weighting agreement (Spearman rank correlation)\n")
    sp = V["vulnerability"]["spearman"]
    w("| | Equal | Expert | PCA | Supplied HVI |\n| --- | --- | --- | --- | --- |")
    for k, name in (("vuln_equal", "Equal"), ("vuln_expert", "Expert"), ("vuln_pca", "PCA"), ("hvi_score", "Supplied HVI")):
        w(f"| {name} | " + " | ".join(f(sp[k][c], 2) for c in ("vuln_equal", "vuln_expert", "vuln_pca", "hvi_score")) + " |")
    w("\nEqual and expert weightings agree almost perfectly. PCA disagrees because its first component picks up urbanisation, "
      "along which exposure rises while adaptive-capacity deficits fall — the two cancel in a single component.\n")

    w("## 8. Test suites\n")
    w("| Suite | Scope |\n| --- | --- |")
    w("| `tests/test_indices_reference.py` | WBGT, UTCI, Heat Index, psychrometrics against published reference values and physical invariants; real-data plausibility; the hourly-vs-daily regression |")
    w("| `tests/test_places_and_risk.py` | crosswalk, cell assignment, de-duplication, baseline, NFHS-5 spot checks, vulnerability, risk-model maths, heat-season regression |")
    w("| `server/test/*.test.js` | HAP state machine (anticipation, hysteresis, no flapping), advisories in three languages, CAP 1.2 structure, channels, optimiser, full API |")
    w("")

    out = ROOT / "docs" / "11_VALIDATION_REPORT.md"
    out.write_text("\n".join(L), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
