// Common Alerting Protocol 1.2 (OASIS) documents.
//
// CAP is the XML format national alerting platforms consume -- India's
// NDMA-led integrated alert system among them. Emitting valid CAP means an
// USHMA alert can be ingested by an existing dissemination system without a
// bespoke integration.
//
// Replay alerts are issued with status "Exercise": they describe a historical
// period and must never be mistaken for a live warning by a downstream system.

import { config } from "../config.js";
import { renderAdvisory } from "./advisory.js";

const esc = (s) =>
  String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");

const SEVERITY = { Watch: "Moderate", Warning: "Severe", Emergency: "Extreme" };
const URGENCY = (lead) => (lead <= 0 ? "Immediate" : lead <= 2 ? "Expected" : "Future");
const CERTAINTY = (lead, p) => (lead <= 0 ? "Observed" : (p ?? 0) >= 0.5 ? "Likely" : "Possible");
const RESPONSE = { Watch: "Prepare", Warning: "Avoid", Emergency: "Shelter" };

/** ISO-8601 with the IST offset, as CAP requires an explicit offset. */
export function istTimestamp(date = new Date()) {
  const ist = new Date(date.getTime() + 5.5 * 3600_000);
  return ist.toISOString().replace(/\.\d{3}Z$/, "+05:30");
}

function capPolygon(geometry) {
  // CAP polygons are "lat,lon" pairs, space-separated, first point repeated.
  const ring = geometry.type === "MultiPolygon" ? geometry.coordinates[0][0] : geometry.coordinates[0];
  const pts = ring.map(([lon, lat]) => `${lat.toFixed(5)},${lon.toFixed(5)}`);
  if (pts[0] !== pts.at(-1)) pts.push(pts[0]);
  return pts.join(" ");
}

/**
 * Build one CAP 1.2 alert.
 * @param {object} a { id, level, lead, day, place, geometry, areaCode, mode, msgType, references, sent }
 */
export function buildCap(a) {
  const langs = ["en", "hi", "or"];
  const sent = a.sent ?? istTimestamp();
  const onset = `${a.day.date}T00:00:00+05:30`;
  const expires = `${a.day.date}T23:59:59+05:30`;
  const status = a.mode === "live" ? "Actual" : "Exercise";

  const infos = langs.map((lang) => {
    const adv = renderAdvisory({ place: a.place, level: a.level, lead: a.lead, day: a.day, lang, audience: "public" });
    return `  <info>
    <language>${lang === "en" ? "en-IN" : lang === "hi" ? "hi-IN" : "or-IN"}</language>
    <category>Met</category>
    <category>Health</category>
    <event>${esc(adv.levelLabel)}</event>
    <responseType>${RESPONSE[a.level] ?? "Monitor"}</responseType>
    <urgency>${URGENCY(a.lead)}</urgency>
    <severity>${SEVERITY[a.level] ?? "Minor"}</severity>
    <certainty>${CERTAINTY(a.lead, a.day.pWarning)}</certainty>
    <eventCode><valueName>USHMA</valueName><value>HEAT-${a.level.toUpperCase()}</value></eventCode>
    <effective>${sent}</effective>
    <onset>${onset}</onset>
    <expires>${expires}</expires>
    <senderName>${esc(config.cap.senderName)}</senderName>
    <headline>${esc(adv.headline)}</headline>
    <description>${esc(adv.description)}</description>
    <instruction>${esc(adv.actions.join(" "))}</instruction>
    <parameter><valueName>HTSI</valueName><value>${a.day.htsi ?? ""}</value></parameter>
    <parameter><valueName>HTSI_80PCT_BAND</valueName><value>${a.day.q10 ?? ""}-${a.day.q90 ?? ""}</value></parameter>
    <parameter><valueName>MRI</valueName><value>${a.day.mri ?? ""}</value></parameter>
    <parameter><valueName>WBGT_MAX_C</valueName><value>${a.day.wbgt ?? ""}</value></parameter>
    <area>
      <areaDesc>${esc(a.place)}</areaDesc>
${a.geometry ? `      <polygon>${capPolygon(a.geometry)}</polygon>\n` : ""}      <geocode><valueName>USHMA_AREA</valueName><value>${esc(a.areaCode)}</value></geocode>
    </area>
  </info>`;
  });

  return `<?xml version="1.0" encoding="UTF-8"?>
<alert xmlns="urn:oasis:names:tc:emergency:cap:1.2">
  <identifier>${esc(a.id)}</identifier>
  <sender>${esc(config.cap.sender)}</sender>
  <sent>${sent}</sent>
  <status>${status}</status>
  <msgType>${a.msgType ?? "Alert"}</msgType>
  <scope>Public</scope>
${status === "Exercise" ? "  <note>Historical replay generated by USHMA for demonstration. Not a live warning.</note>\n" : ""}${a.references ? `  <references>${esc(a.references)}</references>\n` : ""}${infos.join("\n")}
</alert>
`;
}
